///////////////////////////////////////////////////////////////////////////////////////
///////// > openSMILE eGeMAPSv02 external audio configuration ////////////////////////
///////////////////////////////////////////////////////////////////////////////////////

[componentInstances:cComponentManager]

instance[dataMemory].type=cDataMemory
instance[externalAudioSource].type=cExternalAudioSource
instance[lldconcat].type=cVectorConcat
instance[funcconcat].type=cVectorConcat
instance[externalSink].type=cExternalSink

printLevelStats=5
profiling=1
nThreads=1


[externalAudioSource:cExternalAudioSource]

writer.dmLevel = wave
sampleRate = 16000
channels = 1
nBits = 16
nBPS = 0
blocksize = 25600
fieldName = pcm


\{gemaps/v01b/GeMAPSv01b_core.lld.conf.inc}
\{egemaps/v02/eGeMAPSv02_core.lld.conf.inc}
\{gemaps/v01b/GeMAPSv01b_core.func.conf.inc}
\{egemaps/v02/eGeMAPSv02_core.func.conf.inc}

[lldconcat:cVectorConcat]

reader.dmLevel = egemapsv02_lldsetE_smo;egemapsv02_lldsetF_smo
writer.dmLevel = lld
includeSingleElementFields = 1


[funcconcat:cVectorConcat]

reader.dmLevel = gemapsv01b_functionalsF0;gemapsv01b_functionalsLoudness;egemapsv02_functionalsMeanStddevZ;egemapsv02_functionalsMeanStddevVoiced;egemapsv02_functionalsMeanUnvoiced;gemapsv01b_temporalSet;egemapsv02_leq

writer.dmLevel = func
includeSingleElementFields = 1


[externalSink:cExternalSink]

reader.dmLevel = func
