
[componentInstances:cComponentManager]

instance[dataMemory].type=cDataMemory
instance[externalAudioSource].type=cExternalAudioSource
instance[externalSink].type=cExternalSink

printLevelStats=5
profiling=0
nThreads=1


[externalAudioSource:cExternalAudioSource]

writer.dmLevel = wave

sampleRate = 16000
channels = 1
nBits = 16
nBPS = 0

blocksize = 25600
fieldName = pcm


\{gemaps/v01b/GeMAPSv01b_core.lld.conf.inc}

\{egemaps/v02/eGeMAPSv02_core.lld.conf.inc}


[externalSink:cExternalSink]

reader.dmLevel = egemapsv02_lldSetSelectorE

numberElements = 0
numberFields = 0
