[componentInstances:cComponentManager]

instance[dataMemory].type=cDataMemory

instance[externalAudioSource].type=cExternalAudioSource

[externalAudioSource:cExternalAudioSource]

writer.dmLevel = wave

sampleRate = 16000

channels = 1

nBits = 16

nBPS = 0

blocksize = 25600

fieldName = pcm